# Generated by Django 5.0.6 on 2024-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='booking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TimeField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('15:00', '15:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('17:00', '17:00')]),
        ),
    ]
